name: Deploy to Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayhq/railway-action@v1
        with:
          token: ${{ secrets.RAILWAY_TOKEN }}
          project: 88608be2-ded4-486b-9f93-e02720e62e3c
          environment: production
